Rails.application.routes.draw do
  get '/breweries', to: 'breweries#index'
  get '/breweries/new', to: 'breweries#new'
  get '/breweries/:id/edit', to: 'breweries#edit'
  post '/breweries', to: 'breweries#create'
  patch '/breweries/:id', to: 'breweries#update'
  get '/breweries/:id', to: 'breweries#show'
  get '/beers', to: 'beers#index'
  get '/beers/:id', to: 'beers#show'
  get '/breweries/:id/beers', to: 'beers#show_by_brewery'
  get '/breweries/:id/beers/sorted', to: 'beers#show_by_brewery_alphabetically'
  post '/breweries/:id/beers', to: 'beers#create'
  get '/breweries/:id/beers/new', to: 'beers#new'
  get '/beers/:id/edit', to: 'beers#edit'
  patch '/beers/:id', to: 'beers#update'
  delete '/breweries/:id', to: 'breweries#destroy'
  delete '/beers/:id', to: 'beers#destroy'
end
